name: InvSeeker
version: '1.5.3'
main: org.plugin.invseeker.InvSeeker
api-version: '1.20'
load: STARTUP
authors: [NSrank & Qwen2.5-Max]

commands:
  invsee:
    description: 主插件命令
    usage: /invsee <子命令>
    permission: invseeker.view
    aliases: [ isee ]
    subcommands:
      reload:
        description: 重载配置文件
        usage: /invsee reload
        permission: invseeker.admin
      help:
        description: 显示帮助信息
        usage: /invsee help
        permission: invseeker.view

  endersee:
    description: 查看玩家末影箱
    usage: /endersee <玩家名>
    permission: invseeker.view


permissions:
  invsee.view:
    description: 允许查看玩家背包和末影箱
    default: op
  invsee.admin:
    description: 允许重载插件配置
    default: op